# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 18:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_auto_20170504_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='text',
        ),
    ]
